/**
 * Tunable game parameters. Change values here instead of rewriting systems.
 * This prototype uses virtual chips only — no real-money economy.
 */
export const gameConfig = {
  title: 'Runway at Sea',
  startingBalance: 1000,
  currencyCode: 'VC',
  storageKey: 'runway-at-sea:v1',

  betting: {
    min: 10,
    max: 200,
    defaultAmount: 20,
    presets: [10, 20, 50, 100, 200],
    step: 10,
  },

  /**
   * SUCCESS / FAIL odds. Values are normalized if they do not sum to 1.
   */
  successProbability: 0.35,
  failProbability: 0.65,

  multiplier: {
    start: 1,
    decimals: 2,
    success: {
      min: 1.35,
      max: 6.8,
      weights: { altitude: 0.45, distance: 0.35, duration: 0.2 },
    },
    fail: {
      min: 1.2,
      max: 2.7,
      settled: 0,
      weights: { altitude: 0.4, distance: 0.4, duration: 0.2 },
    },
    phases: {
      TAKEOFF: { at: 0.14, progress: 0.14 },
      CLIMB: { at: 0.32, progress: 0.46 },
      CRUISE: { at: 0.58, progress: 0.72 },
      DESCENT: { at: 0.82, progress: 0.9 },
      LANDING: { at: 1, progress: 1 },
      CRASH: { at: 1, progress: 0 },
    },
  },

  /**
   * Controlled spread per outcome. SUCCESS stays inside the landing zone;
   * FAIL is always past the deck so the plane cannot land.
   */
  roundResult: {
    landingZone: { start: 1288, end: 1435 },
    success: {
      targetDistance: { min: 1300, max: 1410 },
      maxAltitude: { min: 150, max: 230 },
      flightDuration: { min: 5.4, max: 7.2 },
      multiplier: { min: 1.35, max: 6.8 },
    },
    fail: {
      targetDistance: { min: 1490, max: 1640 },
      maxAltitude: { min: 155, max: 235 },
      flightDuration: { min: 5.3, max: 7.1 },
      multiplier: { min: 1.2, max: 2.7 },
      minOvershoot: 40,
    },
  },

  scene: {
    horizonRatio: 0.58,
    imageHorizon: 0.62,
    viewRange: 240,
    cameraFollow: 0.3,
    maxCameraOrigin: 100000,
    followLookAhead: 0.28,
    followDamping: 16,
    followSpeedLead: 0.04,
    followLift: 0.72,
    followKeepAlt: 64,
    followMinVisAlt: 32,
    followMaxVisAlt: 96,
    followMaxLag: 0.16,
    followXMin: 0.14,
    followXMax: 0.52,
    followYMin: 0.18,
    followYMax: 0.58,
    followMaxOrigin: 100000,
    lateralFactor: 0,
    sway: 3,
    perspective: 1,
    nearScale: 1,
    farScale: 1,
    altScale: 1.22,
    waterY: 0.72,
    planeX: 0.3,
    /**
     * World-space visual sizes. Drawn via camera ppm so they stay
     * aligned with colliders (distance/altitude, not screen %).
     */
    objectScale: {
      planeWorldLength: 48,
      shipWorldLength: 176,
      shipHalfW: 84,
      shipHalfH: 18,
      numberWorldSize: 9,
      numberObjectScale: 1,
      rocketWorldLength: 26,
    },
    track: {
      length: 2100,
      seed: 47,
      poolSize: 16,
      maxVisible: 3,
      spawnAhead: 720,
      minGap: 400,
      maxGap: 880,
      keepOutBeforeTarget: 260,
      keepOutAfterTarget: 280,
      drift: 6,
      lateralMin: 0,
      lateralMax: 0,
      yawMin: 0,
      yawMax: 0,
      scaleMin: 1,
      scaleMax: 1,
    },
    /**
     * Idle establishing shot. Gameplay follow still uses the values above;
     * CameraRig blends from this framing to the follow camera after START.
     */
    cameraIntro: {
      origin: -48,
      viewRange: 240,
      nearScale: 1,
      farScale: 1,
      nearX: 0.32,
      farX: 0.32,
      nearWater: 0.74,
      planeX: 0.32,
      lift: 2,
      sway: 0.12,
      perspective: 1,
      blendDuration: 0.28,
      returnDuration: 0.45,
      poseRelease: 0.1,
      planeOnDeck: 0.27,
      deckX: 0.46,
      deckY: 0.34,
      homeScale: 1,
      tall: {
        viewRange: 240,
        nearScale: 1,
        nearX: 0.34,
        farX: 0.34,
        nearWater: 0.76,
        planeX: 0.34,
        planeOnDeck: 0.27,
        deckX: 0.48,
        deckY: 0.34,
        homeScale: 1,
      },
    },
    assets: {
      sky: './assets/scene-sky-ocean.png',
      carrier: './assets/sprite-carrier.png?v=side',
      plane: './assets/sprite-plane.png',
    },
  },

  flight: {
    world: {
      shipDistance: 1280,
      deckAltitude: 26,
      deckLength: 170,
      waterLevel: 0,
      startDistance: 48,
      startAltitude: 26,
    },
    path: {
      startPosition: { distance: 48, altitude: 26 },
      targetDistance: 1280,
      maxAltitude: { min: 150, max: 230 },
      flightDuration: { min: 5.4, max: 7.2 },
      takeoffDuration: { min: 0.7, max: 1.05 },
      climbDuration: { min: 1.05, max: 1.6 },
      cruiseDuration: { min: 1.35, max: 2.1 },
      descentDuration: { min: 1.15, max: 1.7 },
      landingDuration: { min: 0.85, max: 1.2 },
      crashDuration: { min: 0.75, max: 1.15 },
      horizontalSpeed: { min: 210, max: 320 },
      verticalSpeed: { min: 70, max: 120 },
      landingAngle: { min: -9, max: -4.5 },
      crashPoint: { min: 80, max: 190 },
      smoothing: 14,
      pitchSmoothing: 11,
      maxDt: 0.05,
    },
    touchdownSpeed: 78,
    landing: {
      success: {
        approachDuration: 0.38,
        decelerateDuration: 0.42,
        descendDuration: 0.4,
        flareDuration: 0.36,
        alignDuration: 0.28,
        settleDuration: 0.72,
        stopDuration: 0.48,
        approachSpeed: 92,
        touchdownSpeed: 28,
        flareAltitude: 18,
        maxSink: 44,
        approachPitch: -8,
        flarePitch: 6.2,
        alignPitch: 0,
        bounce: 4.8,
        spring: 46,
        damping: 14,
        brake: 3.1,
      },
      fail: {
        criticalDuration: 0.72,
        missDuration: 0.82,
        overshootDuration: 0.35,
        stallDuration: 0.4,
        diveDuration: 0.55,
        fallDuration: 1.25,
        carryDuration: 0.72,
        waterHold: 0.55,
        shortfall: 24,
        missClearance: 22,
        gravity: 155,
        divePitch: -38,
      },
    },
  },

  roundResetDelayMs: 1700,
  landingResultDelayMs: 360,
  historyLimit: 16,
  playbackSpeeds: [1, 1.5, 2, 3],
  defaultPlaybackSpeed: 1,

  numberPickups: {
    minCount: 28,
    extraCount: 10,
    numberMin: 1,
    numberMax: 10,
    seed: 91,
    uStart: 0.04,
    uEnd: 0.98,
    minSeparation: 36,
    startDistance: 56,
    gapMin: 28,
    gapMax: 86,
    spawnAhead: 460,
    despawnBehind: 240,
    maxLive: 72,
    altitudeJitter: 22,
    distanceJitter: 36,
    altitudeBands: [-52, -32, -14, 4, 22, 44, 72, 98],
    waveMin: 36,
    waveMax: 270,
    waveStep: 38,
    lateralMin: 28,
    lateralMax: 148,
    planeRadius: 18,
    numberRadius: 8,
    multiplierBonus: 0.06,
  },

  rockets: {
    minCount: 20,
    extraCount: 8,
    seed: 113,
    uStart: 0.08,
    uEnd: 0.96,
    minSeparation: 70,
    startDistance: 100,
    gapMin: 54,
    gapMax: 140,
    spawnAhead: 480,
    despawnBehind: 260,
    maxLive: 48,
    altitudeBands: [-46, -24, -6, 12, 34, 58, 86],
    altitudeJitter: 16,
    distanceJitter: 28,
    waveMin: 36,
    waveMax: 270,
    waveStep: 42,
    radius: 12,
    angleMin: -32,
    angleMax: 36,
    bobMin: 3,
    bobMax: 9,
    driftMin: 2,
    driftMax: 8,
    rocketMultiplierPenalty: 0.18,
    rocketAltitudePenalty: 34,
    rocketSpeedPenalty: 0.12,
    rocketSpeedDelta: 42,
    rocketDamage: 0.2,
    criticalDamage: 0.75,
    rocketEffectDuration: 0.9,
    maxAltitudeDrop: 40,
    minSpeedMul: 0.55,
    minMultiplier: 1,
  },

  physics: {
    gravity: 38,
    crashGravity: 155,
    landingGravity: 11,
    drag: 1.8,
    lift: 2.4,
    steer: 9,
    landingSteer: 6.5,
    crashSteer: 2.4,
    maxSpeed: 420,
    minAltitude: 8,
    maxAltitude: 360,
    minDistance: 0,
    maxDistance: 100000,
    maxImpulse: 90,
    numberNudge: 38,
    numberSpeedBoost: 40,
    numberRepair: 0.04,
    stallSpeed: 72,
    stallAltitude: 22,
    holdSpeed: 96,
    launchVx: 198,
    launchVy: 300,
    launchPitch: 0,
    launchBoost: 0.98,
    launchHoldAltitude: 320,
    holdPitchMax: 0,
    launchSteer: 22,
    launchLift: 8.5,
    holdLock: 7.5,
    glideGravity: 0,
    minHoldSpeed: 18,
    criticalDamage: 0.75,
    angularDamp: 10,
    maxAngular: 80,
    planeRadius: 18,
    minSpeedMul: 0.55,
    crashCatchup: 2.4,
    crashBlend: 1.2,
    damageGravity: 22,
    flightDamageCap: 0.45,
    maxDamage: 1.25,
    landingVyDamp: 8,
    landingBrake: 7.5,
  },
};
