/**
 * Tunable game parameters. Change values here instead of rewriting systems.
 * This prototype uses virtual chips only — no real-money economy.
 */
export const gameConfig = {
  title: 'Runway at Sea',
  startingBalance: 1000,
  currencyCode: 'VC',
  storageKey: 'runway-at-sea:v1',

  betting: {
    min: 10,
    max: 200,
    defaultAmount: 20,
    presets: [10, 20, 50, 100, 200],
    step: 10,
  },

  /**
   * SUCCESS / FAIL odds. Values are normalized if they do not sum to 1.
   */
  successProbability: 0.35,
  failProbability: 0.65,

  multiplier: {
    start: 1,
    decimals: 2,
    success: {
      min: 1.35,
      max: 6.8,
      weights: { altitude: 0.45, distance: 0.35, duration: 0.2 },
    },
    fail: {
      min: 1.2,
      max: 2.7,
      settled: 0,
      weights: { altitude: 0.4, distance: 0.4, duration: 0.2 },
    },
    phases: {
      TAKEOFF: { at: 0.14, progress: 0.14 },
      CLIMB: { at: 0.32, progress: 0.46 },
      CRUISE: { at: 0.58, progress: 0.72 },
      DESCENT: { at: 0.82, progress: 0.9 },
      LANDING: { at: 1, progress: 1 },
      CRASH: { at: 1, progress: 0 },
    },
  },

  /**
   * Controlled spread per outcome. SUCCESS stays inside the landing zone;
   * FAIL is always past the deck so the plane cannot land.
   */
  roundResult: {
    landingZone: { start: 1288, end: 1435 },
    success: {
      targetDistance: { min: 1300, max: 1410 },
      maxAltitude: { min: 150, max: 230 },
      flightDuration: { min: 5.4, max: 7.2 },
      multiplier: { min: 1.35, max: 6.8 },
    },
    fail: {
      targetDistance: { min: 1490, max: 1640 },
      maxAltitude: { min: 155, max: 235 },
      flightDuration: { min: 5.3, max: 7.1 },
      multiplier: { min: 1.2, max: 2.7 },
      minOvershoot: 40,
    },
  },

  scene: {
    horizonRatio: 0.4,
    imageHorizon: 0.62,
    viewRange: 320,
    cameraFollow: 0.12,
    maxCameraOrigin: 1850,
    followLookAhead: 0.12,
    followDamping: 8,
    followSpeedLead: 0.02,
    followLift: 0.04,
    followMaxOrigin: 1850,
    lateralFactor: 0.32,
    sway: 5,
    perspective: 1,
    nearScale: 1.72,
    farScale: 0.7,
    track: {
      length: 2100,
      seed: 47,
      poolSize: 2,
      maxVisible: 1,
      gapMin: 170,
      gapMax: 310,
      keepOutBeforeTarget: 240,
      keepOutAfterTarget: 260,
      lateralMin: 0,
      lateralMax: 0,
      yawMin: 0,
      yawMax: 0,
      scaleMin: 1,
      scaleMax: 1,
    },
    /**
     * Idle establishing shot. Gameplay follow still uses the values above;
     * CameraRig blends from this framing to the follow camera after START.
     */
    cameraIntro: {
      origin: 0,
      viewRange: 520,
      nearScale: 1.88,
      farScale: 0.42,
      nearX: 0.28,
      farX: 0.82,
      nearWater: 0.9,
      lift: 4,
      sway: 0.18,
      perspective: 1.08,
      blendDuration: 1.15,
      returnDuration: 0.75,
      poseRelease: 1.1,
      planeOnDeck: 0.18,
      deckX: 0.42,
      deckY: 0.36,
      homeScale: 1.1,
      tall: {
        viewRange: 480,
        nearScale: 1.72,
        nearX: 0.46,
        farX: 0.86,
        nearWater: 0.87,
        planeOnDeck: 0.22,
        deckX: 0.44,
        deckY: 0.36,
        homeScale: 1.08,
      },
    },
    assets: {
      sky: './assets/scene-sky-ocean.png',
      carrier: './assets/sprite-carrier.png?v=side',
      plane: './assets/sprite-plane.png',
    },
  },

  flight: {
    world: {
      shipDistance: 1280,
      deckAltitude: 26,
      deckLength: 170,
      waterLevel: 0,
      startDistance: 48,
      startAltitude: 26,
    },
    path: {
      startPosition: { distance: 48, altitude: 26 },
      targetDistance: 1280,
      maxAltitude: { min: 150, max: 230 },
      flightDuration: { min: 5.4, max: 7.2 },
      takeoffDuration: { min: 0.7, max: 1.05 },
      climbDuration: { min: 1.05, max: 1.6 },
      cruiseDuration: { min: 1.35, max: 2.1 },
      descentDuration: { min: 1.15, max: 1.7 },
      landingDuration: { min: 0.85, max: 1.2 },
      crashDuration: { min: 0.75, max: 1.15 },
      horizontalSpeed: { min: 210, max: 320 },
      verticalSpeed: { min: 70, max: 120 },
      landingAngle: { min: -9, max: -4.5 },
      crashPoint: { min: 80, max: 190 },
      smoothing: 14,
      pitchSmoothing: 11,
      maxDt: 0.05,
    },
    touchdownSpeed: 78,
    landing: {
      success: {
        approachDuration: 0.38,
        decelerateDuration: 0.42,
        descendDuration: 0.4,
        flareDuration: 0.36,
        alignDuration: 0.28,
        settleDuration: 0.52,
        stopDuration: 0.38,
        approachSpeed: 96,
        touchdownSpeed: 36,
        flareAltitude: 16,
        approachPitch: -7.5,
        flarePitch: 5.5,
        alignPitch: 0,
        bounce: 7.4,
        spring: 62,
        damping: 12,
        brake: 4.4,
      },
      fail: {
        criticalDuration: 0.38,
        missDuration: 0.42,
        overshootDuration: 0.4,
        stallDuration: 0.32,
        diveDuration: 0.28,
        fallDuration: 0.85,
        missClearance: 22,
        gravity: 240,
        divePitch: -38,
      },
    },
  },

  roundResetDelayMs: 1700,
  landingResultDelayMs: 360,
  historyLimit: 16,
  playbackSpeeds: [1, 1.5, 2, 3],
  defaultPlaybackSpeed: 1,

  numberPickups: {
    minCount: 20,
    extraCount: 6,
    numberMin: 1,
    numberMax: 10,
    seed: 91,
    uStart: 0.06,
    uEnd: 0.9,
    minSeparation: 28,
    altitudeJitter: 42,
    distanceJitter: 64,
    altitudeBands: [-92, -58, -30, -8, 14, 40, 72, 108],
    lateralMin: 28,
    lateralMax: 148,
    planeRadius: 18,
    numberRadius: 15,
  },

  rockets: {
    minCount: 20,
    extraCount: 5,
    seed: 113,
    uStart: 0.11,
    uEnd: 0.84,
    minSeparation: 56,
    altitudeBands: [-56, -28, 8, 36, 64],
    altitudeJitter: 12,
    distanceJitter: 16,
    radius: 16,
    angleMin: -32,
    angleMax: 36,
    bobMin: 3,
    bobMax: 9,
    driftMin: 2,
    driftMax: 8,
    rocketMultiplierPenalty: 0.18,
    rocketAltitudePenalty: 14,
    rocketSpeedPenalty: 0.22,
    rocketEffectDuration: 0.9,
    maxAltitudeDrop: 40,
    minSpeedMul: 0.55,
    minMultiplier: 1,
  },

  physics: {
    gravity: 38,
    crashGravity: 220,
    landingGravity: 8,
    drag: 1.8,
    lift: 2.4,
    steer: 9,
    landingSteer: 16,
    crashSteer: 3.2,
    maxSpeed: 420,
    minAltitude: 8,
    maxAltitude: 360,
    minDistance: 0,
    maxDistance: 2400,
    maxImpulse: 90,
    numberNudge: 4,
    angularDamp: 10,
    maxAngular: 80,
    planeRadius: 18,
    minSpeedMul: 0.55,
    crashCatchup: 11,
    landingVyDamp: 14,
    landingBrake: 10,
  },
};
